/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Coordinate = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const LocationEntry = IDL.Record({
  'valleyName' : IDL.Text,
  'mountainName' : IDL.Text,
  'notes' : IDL.Text,
  'governorate' : IDL.Text,
  'coordinate' : Coordinate,
  'location' : IDL.Text,
});
export const BirdData = IDL.Record({
  'id' : IDL.Nat,
  'subImages' : IDL.Vec(IDL.Text),
  'localName' : IDL.Text,
  'description' : IDL.Text,
  'audioFile' : IDL.Opt(IDL.Text),
  'arabicName' : IDL.Text,
  'englishName' : IDL.Text,
  'notes' : IDL.Text,
  'scientificName' : IDL.Text,
  'locations' : IDL.Vec(LocationEntry),
});
export const LocationData = IDL.Record({
  'birdName' : IDL.Text,
  'coordinate' : Coordinate,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const TeamGroup = IDL.Record({
  'members' : IDL.Vec(IDL.Text),
  'projectManagers' : IDL.Vec(IDL.Text),
  'designers' : IDL.Vec(IDL.Text),
  'followers' : IDL.Vec(IDL.Text),
});
export const TeamMember = IDL.Record({
  'residence' : IDL.Text,
  'fullNameTribe' : IDL.Text,
  'university' : IDL.Text,
  'number' : IDL.Int,
  'timestamp' : IDL.Int,
  'specialization' : IDL.Text,
  'contactNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAudioFile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addBirdData' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addBirdWithDetails' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'addOrUpdateBird' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'addSubImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'birdExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'canCallerModifyData' : IDL.Func([], [IDL.Bool], ['query']),
  'completeBackupProcess' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
      [],
      [],
    ),
  'conditionalDrop' : IDL.Func([], [], []),
  'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
  'deleteBirdById' : IDL.Func([IDL.Nat], [], []),
  'deleteBirdData' : IDL.Func([IDL.Text], [], []),
  'deleteImageFromBirdAndRegistry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteImageFromGallery' : IDL.Func([IDL.Text], [], []),
  'deleteImageFromGalleryAndBirds' : IDL.Func([IDL.Text], [], []),
  'deleteSubImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'getActiveMapReference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getAllBirdData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
      ['query'],
    ),
  'getAllBirdDetails' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
      ['query'],
    ),
  'getAllCoordinates' : IDL.Func([], [IDL.Vec(Coordinate)], ['query']),
  'getAllLocationsForMap' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LocationData)],
      ['query'],
    ),
  'getAllLocationsWithNames' : IDL.Func([], [IDL.Vec(LocationData)], ['query']),
  'getAllNormalizedBirdNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAudioFile' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getBackupMapReference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getBirdDetails' : IDL.Func([IDL.Text], [IDL.Opt(BirdData)], ['query']),
  'getBirdLocations' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(LocationEntry))],
      ['query'],
    ),
  'getBirdNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getLocationCountByBird' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getSnapshotDetails' : IDL.Func([], [IDL.Text], ['query']),
  'getSubImages' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'getTeamGroups' : IDL.Func([], [TeamGroup], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTotalBirdCount' : IDL.Func([], [IDL.Int], ['query']),
  'getTotalLocationCount' : IDL.Func([], [IDL.Int], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAudioFile' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isBackupProcessActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAuthorizedUser' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'restoreBackupMap' : IDL.Func([], [], []),
  'restoreSnapshot' : IDL.Func([], [], []),
  'saveAllBirdData' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
      [],
      [],
    ),
  'saveBirdData' : IDL.Func([BirdData], [], []),
  'saveBirdDataArray' : IDL.Func([IDL.Vec(BirdData)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveChanges' : IDL.Func([IDL.Text, BirdData], [], []),
  'startBackupProcess' : IDL.Func([], [], []),
  'takeSnapshot' : IDL.Func([], [], []),
  'updateBirdDetails' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateDescriptionAndNotes' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'uploadMapImage' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Coordinate = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const LocationEntry = IDL.Record({
    'valleyName' : IDL.Text,
    'mountainName' : IDL.Text,
    'notes' : IDL.Text,
    'governorate' : IDL.Text,
    'coordinate' : Coordinate,
    'location' : IDL.Text,
  });
  const BirdData = IDL.Record({
    'id' : IDL.Nat,
    'subImages' : IDL.Vec(IDL.Text),
    'localName' : IDL.Text,
    'description' : IDL.Text,
    'audioFile' : IDL.Opt(IDL.Text),
    'arabicName' : IDL.Text,
    'englishName' : IDL.Text,
    'notes' : IDL.Text,
    'scientificName' : IDL.Text,
    'locations' : IDL.Vec(LocationEntry),
  });
  const LocationData = IDL.Record({
    'birdName' : IDL.Text,
    'coordinate' : Coordinate,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const TeamGroup = IDL.Record({
    'members' : IDL.Vec(IDL.Text),
    'projectManagers' : IDL.Vec(IDL.Text),
    'designers' : IDL.Vec(IDL.Text),
    'followers' : IDL.Vec(IDL.Text),
  });
  const TeamMember = IDL.Record({
    'residence' : IDL.Text,
    'fullNameTribe' : IDL.Text,
    'university' : IDL.Text,
    'number' : IDL.Int,
    'timestamp' : IDL.Int,
    'specialization' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAudioFile' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addBirdData' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addBirdWithDetails' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'addOrUpdateBird' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'addSubImage' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'birdExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'canCallerModifyData' : IDL.Func([], [IDL.Bool], ['query']),
    'completeBackupProcess' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
        [],
        [],
      ),
    'conditionalDrop' : IDL.Func([], [], []),
    'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
    'deleteBirdById' : IDL.Func([IDL.Nat], [], []),
    'deleteBirdData' : IDL.Func([IDL.Text], [], []),
    'deleteImageFromBirdAndRegistry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteImageFromGallery' : IDL.Func([IDL.Text], [], []),
    'deleteImageFromGalleryAndBirds' : IDL.Func([IDL.Text], [], []),
    'deleteSubImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'getActiveMapReference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getAllBirdData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
        ['query'],
      ),
    'getAllBirdDetails' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
        ['query'],
      ),
    'getAllCoordinates' : IDL.Func([], [IDL.Vec(Coordinate)], ['query']),
    'getAllLocationsForMap' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LocationData)],
        ['query'],
      ),
    'getAllLocationsWithNames' : IDL.Func(
        [],
        [IDL.Vec(LocationData)],
        ['query'],
      ),
    'getAllNormalizedBirdNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAudioFile' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getBackupMapReference' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getBirdDetails' : IDL.Func([IDL.Text], [IDL.Opt(BirdData)], ['query']),
    'getBirdLocations' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(LocationEntry))],
        ['query'],
      ),
    'getBirdNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getLocationCountByBird' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getSnapshotDetails' : IDL.Func([], [IDL.Text], ['query']),
    'getSubImages' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getTeamGroups' : IDL.Func([], [TeamGroup], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTotalBirdCount' : IDL.Func([], [IDL.Int], ['query']),
    'getTotalLocationCount' : IDL.Func([], [IDL.Int], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAudioFile' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isBackupProcessActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAuthorizedUser' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'restoreBackupMap' : IDL.Func([], [], []),
    'restoreSnapshot' : IDL.Func([], [], []),
    'saveAllBirdData' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, BirdData))],
        [],
        [],
      ),
    'saveBirdData' : IDL.Func([BirdData], [], []),
    'saveBirdDataArray' : IDL.Func([IDL.Vec(BirdData)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveChanges' : IDL.Func([IDL.Text, BirdData], [], []),
    'startBackupProcess' : IDL.Func([], [], []),
    'takeSnapshot' : IDL.Func([], [], []),
    'updateBirdDetails' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateDescriptionAndNotes' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadMapImage' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };