/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BirdData {
  'id' : bigint,
  'subImages' : Array<string>,
  'description' : string,
  'audioFile' : [] | [string],
  'arabicName' : string,
  'englishName' : string,
  'notes' : string,
  'scientificName' : string,
  'locations' : Array<Coordinate>,
}
export interface Coordinate { 'latitude' : number, 'longitude' : number }
export interface FileReference { 'hash' : string, 'path' : string }
export interface LocationData { 'birdName' : string, 'coordinate' : Coordinate }
export interface TeamGroup {
  'members' : Array<string>,
  'projectManagers' : Array<string>,
  'designers' : Array<string>,
  'followers' : Array<string>,
}
export interface TeamMember {
  'residence' : string,
  'fullNameTribe' : string,
  'university' : string,
  'number' : bigint,
  'timestamp' : bigint,
  'specialization' : string,
  'contactNumber' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAudioFile' : ActorMethod<[string, string], string>,
  'addBirdData' : ActorMethod<[string, number, number], undefined>,
  'addBirdWithDetails' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      [] | [string],
      Array<string>,
    ],
    undefined
  >,
  'addOrUpdateBird' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      number,
      number,
      [] | [string],
      Array<string>,
    ],
    undefined
  >,
  'addSubImage' : ActorMethod<[string, string], string>,
  'addTeamMember' : ActorMethod<
    [string, string, string, string, string, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'birdExists' : ActorMethod<[string], boolean>,
  'canCallerModifyData' : ActorMethod<[], boolean>,
  'completeBackupProcess' : ActorMethod<[Array<[string, BirdData]>], undefined>,
  'conditionalDrop' : ActorMethod<[], undefined>,
  'deleteAudioFile' : ActorMethod<[string], undefined>,
  'deleteBirdById' : ActorMethod<[bigint], undefined>,
  'deleteBirdData' : ActorMethod<[string], undefined>,
  'deleteImageFromBirdAndRegistry' : ActorMethod<[string, string], undefined>,
  'deleteImageFromGallery' : ActorMethod<[string], undefined>,
  'deleteImageFromGalleryAndBirds' : ActorMethod<[string], undefined>,
  'deleteSubImage' : ActorMethod<[string, string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'getActiveMapReference' : ActorMethod<[], [] | [string]>,
  'getAllBirdData' : ActorMethod<[], Array<[string, BirdData]>>,
  'getAllBirdDetails' : ActorMethod<[], Array<[string, BirdData]>>,
  'getAllCoordinates' : ActorMethod<[], Array<Coordinate>>,
  'getAllLocationsForMap' : ActorMethod<[string], Array<LocationData>>,
  'getAllLocationsWithNames' : ActorMethod<[], Array<LocationData>>,
  'getAllNormalizedBirdNames' : ActorMethod<[], Array<string>>,
  'getAudioFile' : ActorMethod<[string], [] | [string]>,
  'getBackupMapReference' : ActorMethod<[], [] | [string]>,
  'getBirdDetails' : ActorMethod<[string], [] | [BirdData]>,
  'getBirdLocations' : ActorMethod<[string], [] | [Array<Coordinate>]>,
  'getBirdNames' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getLocationCountByBird' : ActorMethod<[], Array<[string, bigint]>>,
  'getSnapshotDetails' : ActorMethod<[], string>,
  'getSubImages' : ActorMethod<[string], [] | [Array<string>]>,
  'getTeamGroups' : ActorMethod<[], TeamGroup>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getTotalBirdCount' : ActorMethod<[], bigint>,
  'getTotalLocationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAudioFile' : ActorMethod<[string], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isBackupProcessActive' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerAuthorizedUser' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'restoreBackupMap' : ActorMethod<[], undefined>,
  'restoreSnapshot' : ActorMethod<[], undefined>,
  'saveAllBirdData' : ActorMethod<[Array<[string, BirdData]>], undefined>,
  'saveBirdData' : ActorMethod<[BirdData], undefined>,
  'saveBirdDataArray' : ActorMethod<[Array<BirdData>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveChanges' : ActorMethod<[string, BirdData], undefined>,
  'startBackupProcess' : ActorMethod<[], undefined>,
  'takeSnapshot' : ActorMethod<[], undefined>,
  'updateBirdDetails' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'updateDescriptionAndNotes' : ActorMethod<
    [string, string, string],
    undefined
  >,
  'uploadMapImage' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];